on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [linux, windows]

    runs-on: ${{ matrix.os == 'linux' && 'ubuntu-latest' || 'windows-latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: (windows) Install yq
        if: matrix.os == 'windows'
        run: choco install yq -y

      - name: (linux) Install build dependencies
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install pubspec dependencies
        run: flutter pub get

      - name: Build app
        run: flutter build ${{ matrix.os }}

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: build/${{ matrix.os }}/x64/release/bundle
