on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.5.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux app
        run: flutter build linux
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.5.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows
